# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CreateAuthenticationClient.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'google/rpc/status_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "poc.model.CreateAuthenticationClient" do
    optional :authentication_client_type, :enum, 1, "poc.model.AuthenticationClientType"
    optional :client_id, :string, 2
    optional :platform_account_id, :int64, 3
    optional :client_secret, :string, 4
    optional :application_uuid, :string, 5
    optional :enabled, :bool, 6
    optional :user_id, :int64, 7
    optional :api_key, :string, 8
    optional :api_key_name, :string, 9
  end
  add_message "poc.model.AuthenticationClient" do
    optional :authentication_client_type, :enum, 1, "poc.model.AuthenticationClientType"
    optional :client_id, :string, 2
    optional :platform_account_id, :int64, 3
    optional :client_secret, :string, 4
    optional :application_uuid, :string, 5
    optional :enabled, :bool, 6
    optional :user_id, :int64, 7
    optional :api_key, :string, 8
    optional :api_key_name, :string, 9
    optional :created_at, :message, 10, "google.protobuf.Timestamp"
    optional :updated_at, :message, 11, "google.protobuf.Timestamp"
  end
  add_message "poc.model.CreateAuthenticationClientResponse" do
    optional :auth_client, :message, 1, "poc.model.AuthenticationClient"
    optional :status, :message, 2, "google.rpc.Status"
  end
  add_enum "poc.model.AuthenticationClientType" do
    value :AUTHENTICATION_CLIENT_TYPE_UNSPECIFIED, 0
    value :JWT, 1
    value :PUBLIC_TOKEN, 2
    value :PRIVATE_TOKEN, 3
    value :API_KEY, 4
  end
end

module Poc
  module Model
    CreateAuthenticationClient = Google::Protobuf::DescriptorPool.generated_pool.lookup("poc.model.CreateAuthenticationClient").msgclass
    AuthenticationClient = Google::Protobuf::DescriptorPool.generated_pool.lookup("poc.model.AuthenticationClient").msgclass
    CreateAuthenticationClientResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("poc.model.CreateAuthenticationClientResponse").msgclass
    AuthenticationClientType = Google::Protobuf::DescriptorPool.generated_pool.lookup("poc.model.AuthenticationClientType").enummodule
  end
end
