// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: proto/cpf_service.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CpfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cpf         string        `protobuf:"bytes,1,opt,name=cpf,proto3" json:"cpf,omitempty"`
	Validations []*Constraint `protobuf:"bytes,2,rep,name=validations,proto3" json:"validations,omitempty"`
}

func (x *CpfRequest) Reset() {
	*x = CpfRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cpf_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CpfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpfRequest) ProtoMessage() {}

func (x *CpfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cpf_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpfRequest.ProtoReflect.Descriptor instead.
func (*CpfRequest) Descriptor() ([]byte, []int) {
	return file_proto_cpf_service_proto_rawDescGZIP(), []int{0}
}

func (x *CpfRequest) GetCpf() string {
	if x != nil {
		return x.Cpf
	}
	return ""
}

func (x *CpfRequest) GetValidations() []*Constraint {
	if x != nil {
		return x.Validations
	}
	return nil
}

type CpfResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Validations []*ConstraintResponse `protobuf:"bytes,1,rep,name=validations,proto3" json:"validations,omitempty"`
}

func (x *CpfResponse) Reset() {
	*x = CpfResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cpf_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CpfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpfResponse) ProtoMessage() {}

func (x *CpfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cpf_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpfResponse.ProtoReflect.Descriptor instead.
func (*CpfResponse) Descriptor() ([]byte, []int) {
	return file_proto_cpf_service_proto_rawDescGZIP(), []int{1}
}

func (x *CpfResponse) GetValidations() []*ConstraintResponse {
	if x != nil {
		return x.Validations
	}
	return nil
}

type Constraint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Constraint) Reset() {
	*x = Constraint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cpf_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Constraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Constraint) ProtoMessage() {}

func (x *Constraint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cpf_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Constraint.ProtoReflect.Descriptor instead.
func (*Constraint) Descriptor() ([]byte, []int) {
	return file_proto_cpf_service_proto_rawDescGZIP(), []int{2}
}

func (x *Constraint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Constraint) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ConstraintResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value  string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Result bool   `protobuf:"varint,3,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ConstraintResponse) Reset() {
	*x = ConstraintResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cpf_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConstraintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConstraintResponse) ProtoMessage() {}

func (x *ConstraintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cpf_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConstraintResponse.ProtoReflect.Descriptor instead.
func (*ConstraintResponse) Descriptor() ([]byte, []int) {
	return file_proto_cpf_service_proto_rawDescGZIP(), []int{3}
}

func (x *ConstraintResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConstraintResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ConstraintResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_proto_cpf_service_proto protoreflect.FileDescriptor

var file_proto_cpf_service_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x70, 0x66, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22,
	0x52, 0x0a, 0x0a, 0x43, 0x70, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x63, 0x70, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x70, 0x66, 0x12,
	0x32, 0x0a, 0x0b, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x6e, 0x73,
	0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x52, 0x0b, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x22, 0x49, 0x0a, 0x0b, 0x43, 0x70, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0b, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43,
	0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x0b, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x36,
	0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x56, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x41,
	0x0a, 0x0c, 0x43, 0x70, 0x66, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x31,
	0x0a, 0x08, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x10, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x43, 0x70, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x43, 0x70, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6d, 0x61, 0x68, 0x6a, 0x61, 0x64, 0x61, 0x6e, 0x2f, 0x67, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2d, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_cpf_service_proto_rawDescOnce sync.Once
	file_proto_cpf_service_proto_rawDescData = file_proto_cpf_service_proto_rawDesc
)

func file_proto_cpf_service_proto_rawDescGZIP() []byte {
	file_proto_cpf_service_proto_rawDescOnce.Do(func() {
		file_proto_cpf_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_cpf_service_proto_rawDescData)
	})
	return file_proto_cpf_service_proto_rawDescData
}

var file_proto_cpf_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_cpf_service_proto_goTypes = []interface{}{
	(*CpfRequest)(nil),         // 0: grpc.CpfRequest
	(*CpfResponse)(nil),        // 1: grpc.CpfResponse
	(*Constraint)(nil),         // 2: grpc.Constraint
	(*ConstraintResponse)(nil), // 3: grpc.ConstraintResponse
}
var file_proto_cpf_service_proto_depIdxs = []int32{
	2, // 0: grpc.CpfRequest.validations:type_name -> grpc.Constraint
	3, // 1: grpc.CpfResponse.validations:type_name -> grpc.ConstraintResponse
	0, // 2: grpc.CpfValidator.Validate:input_type -> grpc.CpfRequest
	1, // 3: grpc.CpfValidator.Validate:output_type -> grpc.CpfResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_cpf_service_proto_init() }
func file_proto_cpf_service_proto_init() {
	if File_proto_cpf_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_cpf_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CpfRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cpf_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CpfResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cpf_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Constraint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cpf_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConstraintResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_cpf_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cpf_service_proto_goTypes,
		DependencyIndexes: file_proto_cpf_service_proto_depIdxs,
		MessageInfos:      file_proto_cpf_service_proto_msgTypes,
	}.Build()
	File_proto_cpf_service_proto = out.File
	file_proto_cpf_service_proto_rawDesc = nil
	file_proto_cpf_service_proto_goTypes = nil
	file_proto_cpf_service_proto_depIdxs = nil
}
